name: gest-stack

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: gest-mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - gest-net
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost,1433", "-U", "sa", "-C", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s
    volumes:
      - mssql_data:/var/opt/mssql
      - ./docker/sql/init:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: gest-api
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__ConnGest=Server=mssql,1433;Database=GestDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;Encrypt=False;
    ports:
      - "${API_HTTP_PORT}:8080"
    networks:
      - gest-net

networks:
  gest-net:

volumes:
  mssql_data:
